---
cog_bundle_version: 3

name: heroku
version: 0.0.1
description: Interact with heroku
docker:
  image: cogcmd/heroku
  tag: 0.0.1
permissions:
  - heroku:read
  - heroku:write
  - heroku:admin
commands:
  app:
    executable: /home/bundle/cog-command
    description: List and display info about apps
    documentation: |
      heroku:app
      heroku:app list - List all apps
      heroku:app info <app> - Display details about an app
    rules:
      - must have heroku:read
  config:
    executable: /home/bundle/cog-command
    description: List and modify environment variables for an app
    documentation: |
      heroku:config [--app app]
      heroku:config list [--app app] - List all environment variables
      heroku:config set <name=value> [--app app] - Set an environment variable
      heroku:config unset <name> [--app app] - Unset an environment variable
    rules:
      - must have heroku:admin
      - must have heroku:read
      - when arg[0] == 'set' must have heroku:write
      - when arg[0] == 'unset' must have heroku:write
    options:
      app:
        type: string
        required: true
  ps:
    executable: /home/bundle/cog-command
    description: List and modify processes of an app
    documentation: |
      heroku:ps [--app app]
      heroku:ps list [--app app] - List all running processes
      heroku:ps scale [--app app] - Change number of running processes
      heroku:ps restart [--app app] - Restart processes
    rules:
      - must have heroku:read
      - when arg[0] == 'scale' must have heroku:write
      - when arg[0] == 'restart' must have heroku:write
    options:
      app:
        type: string
        required: true
  release:
    executable: /home/bundle/cog-command
    description: List and rollback to older releases
    documentation: |
      heroku:release
      heroku:release list [--app app] - List all releases
      heroku:release info [--app app] - Display details about a release
      heroku:release rollback [--app app] - Rollback the app to a previous release
    rules:
      - must have heroku:read
      - when arg[0] == 'rollback' must have heroku:write
    options:
      app:
        type: string
        required: true
  user:
    executable: /home/bundle/cog-command
    description: List and rollback to older releases
    documentation: |
      heroku:user
      heroku:user list [--app app] - List all users
      heroku:user add [--app app] - Add user by email
      heroku:user remove [--app app] - Remove user by email
    rules:
      - must have heroku:read
      - when arg[0] = 'add' must have heroku:write
      - when arg[0] = 'remove' must have heroku:write
    options:
      app:
        type: string
        required: true
templates:
  app_list:
    slack: "{{name}} - {{owner_email}}"
    hipchat: "{{name}} - {{owner_email}}"
  app_info:
    slack: |
      Dynos: {{dynos}}
      Git URL: {{git_url}}
      Owner: {{owner_email}}
      Region: {{region}}
      Repo Size: {{repo_size}}
      Slug Size: {{slug_size}}
      Stack: {{stack}}
      Web URL: {{web_url}}
    hipchat: |
      Dynos: {{dynos}}
      Git URL: {{git_url}}
      Owner: {{owner_email}}
      Region: {{region}}
      Repo Size: {{repo_size}}
      Slug Size: {{slug_size}}
      Stack: {{stack}}
      Web URL: {{web_url}}
  config_list:
    slack: "{{key}}={{value}}"
    hipchat: "{{key}}={{value}}"
  ps_list:
    slack: "{{process}}: {{command}} ({{pretty_state}})"
    hipchat: "{{process}}: {{command}} ({{pretty_state}})"
  release_list:
    slack: "{{name}} - {{descr}}"
    hipchat: "{{name}} - {{descr}}"
  release_info:
    slack: |
      Name: {{name}}
      Description: {{descr}}
      Released By: {{user}}
      Released At: {{created_at}}
      Commit: {{commit}}
    hipchat: |
      Name: {{name}}
      Description: {{descr}}
      Released By: {{user}}
      Released At: {{created_at}}
      Commit: {{commit}}
  user_list: 
    slack: "{{email}} - {{role}}"
    hipchat: "{{email}} - {{role}}"
