---
cog_bundle_version: 3

name: heroku
version: 0.0.1
description: Interact with heroku
commands:
  app:
    executable: /Users/vanstee/Code/cogcmd/heroku/cog-command
    description: List and display info about apps
    documentation: |
      heroku:app
      heroku:app list - List all apps
      heroku:app info <app> - Display details about an app
    rules:
      - allow
  config:
    executable: /Users/vanstee/Code/cogcmd/heroku/cog-command
    description: List and modify environment variables for an app
    documentation: |
      heroku:config [--app app]
      heroku:config list [--app app] - List all environment variables
      heroku:config set <name=value> [--app app] - Set an environment variable
      heroku:config unset <name> [--app app] - Unset an environment variable
    rules:
      - allow
    options:
      app:
        type: string
        required: true
